source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.4'

use_frameworks!

def shared_pods
end

def shared_ui_pods
  pod 'Kingfisher', '5.15.6'
end

target 'Common' do
    shared_pods
end

target 'CommonTests' do
    shared_pods
end

target 'Directory' do
    shared_pods
    shared_ui_pods
end

target 'DirectoryTests' do
    shared_pods
end

target 'StargazerDirectory' do
    shared_pods
end

target 'StargazerDirectoryTests' do
    shared_pods
end